server:
  port: 8766

## netty服务器端口
netty:
  udp:
    port: 6688
  so:
    rcvbuf: 268435456
    sndbuf: 65536

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1ms
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          auto-add-partitions: true
          min-partition-count: 1
          configuration:
            max.request.size: 12048576
      bindings:
        download-out:
          destination: download-topic
          producer:
            partitionCount: 1             # 大于等于 download service 集群数量
            useNativeEncoding: true
            compressionType: gzip
logging:
  level:
    root: info
